#!/bin/bash

echo "☁️  CloudCode Server - Cloud Deployment Guide"
echo "=============================================="

echo "Choose your deployment platform:"
echo "1) Render.com (Recommended - Easy + Free tier)"
echo "2) Railway.app (Great performance + Simple)"
echo "3) Manual Docker deployment"
echo ""

read -p "Select option (1-3): " choice

case $choice in
    1)
        echo ""
        echo "🎯 RENDER.COM DEPLOYMENT"
        echo "========================"
        echo ""
        echo "📋 Steps to deploy on Render.com:"
        echo ""
        echo "1. Create account at https://render.com"
        echo "2. Connect your GitHub account"
        echo "3. Push this code to your GitHub repository"
        echo "4. Create new Web Service in Render"
        echo "5. Connect your GitHub repo"
        echo "6. Use these settings:"
        echo "   - Environment: Docker"
        echo "   - Build Command: docker build -t cloudcode-server ."
        echo "   - Start Command: /usr/local/bin/start.sh"
        echo "   - Port: 8080"
        echo ""
        echo "7. Set Environment Variables:"
        echo "   PASSWORD=your-secure-password"
        echo "   USER=coder"
        echo "   WORKSPACE=/workspace"
        echo ""
        echo "8. Add Persistent Disk (20GB recommended):"
        echo "   - Name: workspace-data"
        echo "   - Mount Path: /workspace"
        echo ""
        echo "9. Deploy! ✅"
        echo ""
        echo "💡 Pro tip: Use render.yaml for easier deployment"
        echo "   Just upload deploy/render.yaml to your Render dashboard"
        ;;
    2)
        echo ""
        echo "🚂 RAILWAY.APP DEPLOYMENT"
        echo "========================="
        echo ""
        echo "📋 Steps to deploy on Railway.app:"
        echo ""
        echo "1. Create account at https://railway.app"
        echo "2. Install Railway CLI: npm install -g @railway/cli"
        echo "3. Login: railway login"
        echo "4. Deploy: railway up"
        echo ""
        echo "Alternative (GitHub):"
        echo "1. Push code to GitHub"
        echo "2. Create new project in Railway"
        echo "3. Connect GitHub repo"
        echo "4. Set environment variables:"
        echo "   PASSWORD=your-secure-password"
        echo "   USER=coder"
        echo "   WORKSPACE=/workspace"
        echo ""
        echo "5. Add volume:"
        echo "   - Mount path: /workspace"
        echo "   - Size: 20GB"
        echo ""
        echo "6. Deploy! ✅"
        echo ""
        echo "💡 Pro tip: Use railway.json for configuration"
        ;;
    3)
        echo ""
        echo "🐳 MANUAL DOCKER DEPLOYMENT"
        echo "==========================="
        echo ""
        echo "📋 For any cloud provider with Docker support:"
        echo ""
        echo "1. Build and push image:"
        echo "   docker build -t your-registry/cloudcode-server ."
        echo "   docker push your-registry/cloudcode-server"
        echo ""
        echo "2. Run on server:"
        echo "   docker run -d \\"
        echo "     --name cloudcode-server \\"
        echo "     -p 80:8080 \\"
        echo "     -v cloudcode-workspace:/workspace \\"
        echo "     -e PASSWORD=your-secure-password \\"
        echo "     your-registry/cloudcode-server"
        echo ""
        echo "3. Setup reverse proxy (nginx/traefik) for SSL"
        echo "4. Configure domain and firewall"
        echo ""
        ;;
    *)
        echo "Invalid option selected"
        exit 1
        ;;
esac

echo ""
echo "🔒 SECURITY CHECKLIST:"
echo "====================="
echo "✅ Set strong password (min 12 characters)"
echo "✅ Use HTTPS in production (SSL certificate)"
echo "✅ Configure firewall (only ports 80/443 open)"
echo "✅ Regular backups of workspace volume"
echo "✅ Keep Docker image updated"
echo ""

echo "🌐 POST-DEPLOYMENT:"
echo "=================="
echo "After deployment, your CloudCode server will be available at:"
echo "https://your-app-name.onrender.com (Render)"
echo "https://your-app-name.up.railway.app (Railway)"
echo ""
echo "Login with your password and start coding! 🎉"