// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxxuxkdntuiqeogeusxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4eHV4a2RudHVpcWVvZ2V1c3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTY0ODQsImV4cCI6MjA2OTU5MjQ4NH0.rEZueBuW2xp8wakHGCgNVJdoF_1PZB7qLz-8lQqjD38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});